### ISSUE TITLE
pollDnsTxtRecord Namesever IP record type should be configurable

### ISSUE THREAD

**Issue by tiloio** [fishballapp/acme#2]
The Nameserver IP-Adreses in the `pollDnsTxtRecord` are fetched via the `A`-Record.
It fails in my environment because there is only IPv6 traffic allowed.

Can we make this configurable, so the `AAAA`-Record (IPv6) of the Nameservers can be fetched and used?

https://github.com/fishballapp/acme/blob/d1f41e344bce2980cb55ff9aa1a592003977d060/src/Dns01ChallengeUtils.ts#L143

**Comment by ycmjason** [comment]
Good shout! Thanks for the feedback. I agree we should also fetch `AAAA` too.

I can pick this up next!

**Comment by ycmjason** [comment]
Added lookups for `AAAA` records for resolving name server ip addresses.

https://github.com/fishballapp/acme/blob/9b3214991c7ab31972e1f079ab3c94efbe9e4984/src/Dns01ChallengeUtils.ts#L159-L165

I have noticed in the e2e test that github actions doesn't support ipv6. So I ended up with a temporary fix here:

https://github.com/fishballapp/acme/blob/cab448c6ecc54268b2cc1f8eeb62b24380c7aa5b/e2e/workflows.test.ts#L40-L45

This is far from ideal tho. But as a temporary fix to unblock you I've released these changes to version 0.6.0.

I will keep this thread updated as I figure something nicer later! Any suggestions welcome!

**Comment by ycmjason** [comment]
In the latest `0.7.0` version, you non supported ip addresses are stripped away by default. You could also provide a list of name server ip addresses for `pollDnsTxtRecord` to use. This should be more efficient too if you already knew where your domain lives.

See more here: https://jsr.io/@fishballpkg/acme/doc/DnsUtils/~/PollDnsTxtRecordOptions#property_nameserverips
